audit_header: false
title: Albany Real Estate Careers and Training Video Blog with Kevin Clancy
description: Kevin Clancy, a top Real Estate Agent in Albany, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: #
  - title: Free Strategy Call
    url: /contact/
  - title: Free Newsletter
    url: /subscribe/

client:
  name: Kevin Clancy
  title:
  license_number:
  about_markdown: |
    Kevin Clancy is the #1 Realtor in the Capital Region as voted by the Times Union Readers "best of" poll. He has been providing real estate brokerage and appraisal services to the Capital District for over 25 years. He is a New York State licensed real estate broker, Insurance broker, and general certified appraiser. Kevin is a HUD approved broker and started his career specializing in the sale of HUD homes. Kevin's appraisal experience ranges from vacant land and single family homes to multi-tenant office buildings and retail centers.
  market: Albany
  brand: Clancy Real Estate
  brokerage:
  address: 1 Fletcher Road<br>Albany, New York 12203
  phone: 518-861-7016
  phone_type:
  phone2:
  phone2_type:
  email: Kevin@ClancyRealEstate.com
  url: http://ClancyRealEstate.com

CTAs:
  # first_CTA_text: Request a Consultation
  # first_CTA_URL: http://www.albanynyhomevalues.com/
  # second_CTA_text: Home Search
  # second_CTA_URL: http://www.albanyhomefinder.com/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/006.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how we can take your business to new heights."
    CTA_link_text: "Contact Us"
    CTA_url: /contact/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/pages/Clancy-Real-Estate/53079920567
  linkedin_url: https://www.linkedin.com/in/albanynyrealestate
  youtube_url: https://www.youtube.com/channel/UCfdkq316BAtmSHrYxDNlDdA
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Careers and Training Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Careers and Training Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#22933e'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgba(0, 0, 0, .8)

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
